import i18n from "i18next";
import { initReactI18next } from "react-i18next";
import type { Locale } from "../domain/types";

const en = {
  brandTagline: "Your music, in motion.", home: "Home", search: "Search", library: "Library", notifications: "Notifications", more: "More", settings: "Settings", shortcuts: "Keyboard shortcuts", logout: "Sign out",
  login: "Sign in", welcomeBack: "Welcome back", loginSubtitle: "Step into your listening space.", email: "Email", password: "Password", forgotPassword: "Forgot password?", noAccount: "New to Sonora?", createAccount: "Create an account", artistAccount: "Create an artist account", demoAccounts: "Use a demo account", demoPassword: "All demo accounts use", continueAs: "Continue as {{name}}", invalidCredentials: "Email or password is incorrect.",
  register: "Create your Sonora account", artistRegister: "Begin your artist journey", displayName: "Display name", stageName: "Stage name", confirmPassword: "Confirm password", birthDate: "Birth date", gender: "Gender", female: "Female", male: "Male", nonBinary: "Non-binary", preferNot: "Prefer not to say", privacyAccept: "I accept the privacy policy", privacyPolicy: "Privacy policy", listenerRegister: "Listener registration", passwordsMismatch: "Passwords do not match.", required: "This field is required.", accountExists: "Already have an account?", resetTitle: "Reset your password", resetHelp: "In this frontend mock, use a demo account or reset local demo data in Settings.", backToLogin: "Back to sign in",
  greetingMorning: "Good morning", greetingAfternoon: "Good afternoon", greetingEvening: "Good evening", weeklySound: "Your week in sound", minutesListened: "minutes listened", topMood: "top mood", listeningStreak: "day listening streak", recentlyPlayed: "Recently played", newReleases: "New releases", popularTracks: "Popular right now", earlyAccess: "Gold early access", followedRelease: "New from artists you follow", play: "Play", pause: "Pause", next: "Next", previous: "Previous", like: "Like", unlike: "Unlike", addNext: "Play next", addQueue: "Add to queue", explicit: "Explicit", locked: "Locked", goldRequired: "Gold access required", explicitRestricted: "Explicit content is restricted", dailyLimit: "Daily stream limit reached", verified: "Verified artist", newBadge: "New",
  searchTitle: "Find your next sound", searchPlaceholder: "Search tracks, artists, releases, and playlists", people: "People", artists: "Artists", tracks: "Tracks", releases: "Releases", playlists: "Playlists", sortPopular: "Most listeners", sortNewest: "Newest", allGenres: "All genres", noResults: "No echoes yet", noResultsBody: "Try another title, artist, or genre.",
  yourLibrary: "Your library", likedSongs: "Liked Songs", ownedPlaylists: "Your playlists", savedPlaylists: "Saved playlists", recentHistory: "Listening history", createPlaylist: "Create playlist", playlistName: "Playlist name", create: "Create", save: "Save", saved: "Saved", unsave: "Remove from library", public: "Public", private: "Private", edit: "Edit", delete: "Delete", rename: "Rename", description: "Description", playlistEmpty: "A quiet playlist", playlistEmptyBody: "Add tracks from Search to give it a pulse.", owner: "By {{name}}", tracksCount: "{{count}} tracks", dragHelp: "Use drag handles or keyboard controls to reorder.", deleteConfirm: "Delete this playlist?", liveReference: "Live reference — owner changes appear here.", playlistLimit: "Your plan's playlist limit has been reached.",
  settingsTitle: "Settings", appearance: "Appearance", language: "Language", theme: "Theme", dark: "Dark", light: "Light", system: "System", content: "Content", explicitSetting: "Allow explicit content", explicitMinor: "Explicit audio stays blocked for listeners under 18.", notificationMode: "Notification delivery", timezone: "Timezone", subscription: "Subscription", currentPlan: "Current plan", upgrade: "Explore plans", account: "Account", deleteAccount: "Delete account", deleteWarning: "This hides your profile, revokes this session, and removes public access in the local mock.", resetDemo: "Reset demo data", resetDemoHelp: "Restore all seeded accounts and remove local changes.", profileImageGate: "Profile images require Silver or Gold.", roomsGate: "Group Listening arrives in integration and requires Silver or Gold.", demoSimulation: "Demo simulation — no real charge", toman: "toman", perMonth: "/ month", choosePlan: "Choose {{tier}}", activePlan: "Current", sameTierBlocked: "Active plans cannot be stacked.", downgradeBlocked: "Silver is available after Gold expires.", checkoutComplete: "Demo subscription activated.",
  notificationTitle: "Your signals", markAllRead: "Mark all read", unread: "Unread", read: "Read", remove: "Remove", notificationEmpty: "All caught up", notificationEmptyBody: "New releases, account updates, and social activity will appear here.",
  profile: "Profile", followers: "Followers", following: "Following", follow: "Follow", unfollow: "Following", publicPlaylists: "Public playlists", privateBoundary: "Recently played and Liked Songs are private.", noPublicPlaylists: "No public playlists yet.", artistMetrics: "Artist metrics", listeners: "listeners", streams: "streams", listenerView: "Listener view", artistView: "Artist view",
  release: "Release", album: "Album", single: "Single", released: "Released", releaseDate: "Release date", genre: "Genre", lyrics: "Lyrics", lyricsUnavailable: "No lyrics were provided for this track.", focusMode: "Focus mode", close: "Close", queue: "Queue", queueEmpty: "Your queue is empty", queueEmptyBody: "Play a track or add one from Search.", nowPlaying: "Now playing", removeQueue: "Remove from queue", repeatOff: "Repeat off", repeatAll: "Repeat all", repeatOne: "Repeat one", shuffle: "Shuffle", volume: "Volume", seek: "Seek", playerError: "Playback stopped after repeated media failures.", gestureRequired: "Tap play to allow audio in this browser.", unavailableSkipped: "Unavailable track skipped.",
  studio: "Artist Studio", verification: "Verification", verificationJourney: "Verification journey", profileCreated: "Artist profile created", submitted: "Request submitted", approved: "Approved", rejected: "Rejected", pending: "Pending review", portfolioUrl: "Portfolio URL", note: "Note", submitRequest: "Submit for verification", catalog: "Catalog", releaseHealth: "Release health", healthy: "Healthy", draftUpload: "New release draft", uploadHonesty: "Files are previewed only. Binary media is not persisted or published until the secure Phase 2 backend exists.", audioFile: "Audio file", coverFile: "Cover image", releaseType: "Release type", year: "Year", collaborators: "Collaborators", earlyAccessOption: "Enable Gold early access", saveDraft: "Save metadata draft", draftSaved: "Metadata draft saved. Selected files were not persisted.", verifiedOnly: "Only verified artists can manage releases.", noPublishedCatalog: "Unverified artists do not have a published catalog.", fileTooLarge: "File exceeds the Phase 1 validation limit.", fileTypeInvalid: "Unsupported file type.",
  support: "Support desk", verificationQueue: "Verification queue", approve: "Approve", reject: "Reject", decisionReason: "Decision reason", tickets: "Tickets", ticketSubject: "Subject", newTicket: "New ticket", send: "Send", claim: "Claim", unclaim: "Unclaim", ticketGate: "Tickets require Silver, Gold, or verified artist access.", open: "Open", answered: "Answered", closed: "Closed", noTickets: "No tickets need attention.",
  admin: "Admin console", plans: "Plans", reports: "Reports", revenue: "Revenue", subscriptions: "Subscriptions", audit: "Audit events", payouts: "Payouts", settle: "Settle", settled: "Settled", available: "Available", disabled: "Disabled", discount: "Discount", savePlan: "Save plan", tehranReporting: "Financial reporting timezone: Asia/Tehran", mockData: "Local demonstration data",
  offline: "You're offline", offlineBody: "The app shell remains available, but listening, purchases, uploads, and rooms require a connection.", online: "Back online", install: "Install Sonora", keyboardHelp: "Keyboard help", shortcutSpace: "Play or pause", shortcutNext: "Next track", shortcutPrevious: "Previous track", shortcutLike: "Like current track", shortcutQueue: "Open queue", shortcutMute: "Mute or restore volume", shortcutHelp: "Open shortcut help", key: "Key", action: "Action",
  forbidden: "This space is not available for your account.", notFound: "That page drifted out of range.", goHome: "Go home", loading: "Loading", cancel: "Cancel", confirm: "Confirm", done: "Done", error: "Something went wrong", basic: "Basic", silver: "Silver", gold: "Gold", consumer: "Listener", artist: "Artist", supportRole: "Support", adminRole: "Admin",
  visibility: "Visibility", download: "Downloads", changeAvatar: "Change profile image", avatarUpdated: "Profile image updated", username: "Username", updateUsername: "Update username", usernameHelp: "Lowercase letters, numbers, and underscores. Changeable once every 30 days.", groupListening: "Group Listening", participants: "{{count}} participants", all: "All", importantOnly: "Important only", maxFiveDaily: "Maximum five daily", muted: "Muted", days: "days", monthShort: "mo.", moderation: "Moderation", target: "Target", actor: "Actor", date: "Date", requestId: "Request ID", moderationReason: "Moderation reason", archive: "Archive", audioSpecs: "MP3 · WAV · FLAC · 250 MB", imageSpecs: "JPEG · PNG · WebP · 50 MB", catalogCopyright: "© 2026 Sonora Demo Catalog", sonoraHome: "Sonora home", queueReplaced: "Queue replaced with this context", playingNext: "Playing next", addedQueue: "Added to queue", queueAdvanced: "Queue moved to the next track", privacyLocal: "Sonora’s Phase 1 frontend stores demo and registered-account data only in this browser. Public profiles expose display name, avatar, public playlists, and follower counts. Liked Songs and listening history remain private.", privacyServer: "No account data, selected artist media, payment details, or playback data is sent to a server in this phase. Resetting demo data removes local changes and restores the seeded demonstration.", privacyStaff: "Support and admin identities have no public discovery profiles. Phase 2 will introduce server-side privacy, security, retention, and deletion controls under the authoritative project contract.",
};

type Dictionary = typeof en;
const withEnglish = (translated: Partial<Dictionary>): Dictionary => ({ ...en, ...translated });

const es = withEnglish({ home: "Inicio", search: "Buscar", library: "Biblioteca", notifications: "Notificaciones", more: "Más", settings: "Ajustes", login: "Iniciar sesión", welcomeBack: "Te damos la bienvenida", email: "Correo", password: "Contraseña", createAccount: "Crear una cuenta", recentlyPlayed: "Reproducido recientemente", newReleases: "Nuevos lanzamientos", popularTracks: "Popular ahora", yourLibrary: "Tu biblioteca", likedSongs: "Canciones favoritas", playlists: "Listas", artists: "Artistas", tracks: "Canciones", releases: "Lanzamientos", language: "Idioma", theme: "Tema", subscription: "Suscripción", followers: "Seguidores", following: "Siguiendo", follow: "Seguir", play: "Reproducir", pause: "Pausar", queue: "Cola", lyrics: "Letras", save: "Guardar", delete: "Eliminar", close: "Cerrar", offline: "Sin conexión", logout: "Cerrar sesión", profile: "Perfil", settingsTitle: "Ajustes", notificationTitle: "Tus señales", noResults: "Aún no hay ecos", studio: "Estudio del artista", support: "Soporte", admin: "Consola de administración", public: "Pública", private: "Privada", album: "Álbum", single: "Sencillo", verified: "Artista verificado", createPlaylist: "Crear lista", markAllRead: "Marcar todo como leído", upgrade: "Ver planes", currentPlan: "Plan actual", register: "Crea tu cuenta Sonora", artistRegister: "Comienza tu camino artístico", shortcuts: "Atajos de teclado" });
const de = withEnglish({ home: "Start", search: "Suche", library: "Bibliothek", notifications: "Mitteilungen", more: "Mehr", settings: "Einstellungen", login: "Anmelden", welcomeBack: "Willkommen zurück", email: "E-Mail", password: "Passwort", createAccount: "Konto erstellen", recentlyPlayed: "Zuletzt gehört", newReleases: "Neue Veröffentlichungen", popularTracks: "Gerade beliebt", yourLibrary: "Deine Bibliothek", likedSongs: "Lieblingssongs", playlists: "Playlists", artists: "Künstler", tracks: "Titel", releases: "Veröffentlichungen", language: "Sprache", theme: "Design", subscription: "Abonnement", followers: "Follower", following: "Folgt", follow: "Folgen", play: "Abspielen", pause: "Pause", queue: "Warteschlange", lyrics: "Songtext", save: "Speichern", delete: "Löschen", close: "Schließen", offline: "Du bist offline", logout: "Abmelden", profile: "Profil", settingsTitle: "Einstellungen", notificationTitle: "Deine Signale", noResults: "Noch kein Echo", studio: "Künstlerstudio", support: "Support", admin: "Admin-Konsole", public: "Öffentlich", private: "Privat", album: "Album", single: "Single", verified: "Verifizierter Künstler", createPlaylist: "Playlist erstellen", markAllRead: "Alle als gelesen", upgrade: "Pläne ansehen", currentPlan: "Aktueller Plan", register: "Erstelle dein Sonora-Konto", artistRegister: "Beginne deine Künstlerreise", shortcuts: "Tastenkürzel" });
const fr = withEnglish({ home: "Accueil", search: "Rechercher", library: "Bibliothèque", notifications: "Notifications", more: "Plus", settings: "Réglages", login: "Se connecter", welcomeBack: "Bon retour", email: "E-mail", password: "Mot de passe", createAccount: "Créer un compte", recentlyPlayed: "Écoutés récemment", newReleases: "Nouveautés", popularTracks: "Titres populaires", yourLibrary: "Votre bibliothèque", likedSongs: "Titres aimés", playlists: "Playlists", artists: "Artistes", tracks: "Titres", releases: "Sorties", language: "Langue", theme: "Thème", subscription: "Abonnement", followers: "Abonnés", following: "Abonnements", follow: "Suivre", play: "Lire", pause: "Pause", queue: "File d’attente", lyrics: "Paroles", save: "Enregistrer", delete: "Supprimer", close: "Fermer", offline: "Vous êtes hors ligne", logout: "Se déconnecter", profile: "Profil", settingsTitle: "Réglages", notificationTitle: "Vos signaux", noResults: "Aucun écho", studio: "Studio artiste", support: "Assistance", admin: "Console admin", public: "Publique", private: "Privée", album: "Album", single: "Single", verified: "Artiste vérifié", createPlaylist: "Créer une playlist", markAllRead: "Tout marquer comme lu", upgrade: "Voir les offres", currentPlan: "Offre actuelle", register: "Créez votre compte Sonora", artistRegister: "Commencez votre parcours d’artiste", shortcuts: "Raccourcis clavier" });
const ru = withEnglish({ home: "Главная", search: "Поиск", library: "Медиатека", notifications: "Уведомления", more: "Ещё", settings: "Настройки", login: "Войти", welcomeBack: "С возвращением", email: "Эл. почта", password: "Пароль", createAccount: "Создать аккаунт", recentlyPlayed: "Недавно прослушано", newReleases: "Новые релизы", popularTracks: "Сейчас популярно", yourLibrary: "Ваша медиатека", likedSongs: "Любимые треки", playlists: "Плейлисты", artists: "Исполнители", tracks: "Треки", releases: "Релизы", language: "Язык", theme: "Тема", subscription: "Подписка", followers: "Подписчики", following: "Подписки", follow: "Подписаться", play: "Играть", pause: "Пауза", queue: "Очередь", lyrics: "Текст", save: "Сохранить", delete: "Удалить", close: "Закрыть", offline: "Нет подключения", logout: "Выйти", profile: "Профиль", settingsTitle: "Настройки", notificationTitle: "Ваши сигналы", noResults: "Пока нет эха", studio: "Студия артиста", support: "Поддержка", admin: "Панель администратора", public: "Открытый", private: "Закрытый", album: "Альбом", single: "Сингл", verified: "Подтверждённый артист", createPlaylist: "Создать плейлист", markAllRead: "Прочитать все", upgrade: "Посмотреть планы", currentPlan: "Текущий план", register: "Создайте аккаунт Sonora", artistRegister: "Начните путь артиста", shortcuts: "Горячие клавиши" });
const zh = withEnglish({ home: "首页", search: "搜索", library: "音乐库", notifications: "通知", more: "更多", settings: "设置", login: "登录", welcomeBack: "欢迎回来", email: "电子邮件", password: "密码", createAccount: "创建账户", recentlyPlayed: "最近播放", newReleases: "新发行", popularTracks: "正在流行", yourLibrary: "你的音乐库", likedSongs: "喜欢的歌曲", playlists: "播放列表", artists: "艺人", tracks: "歌曲", releases: "发行作品", language: "语言", theme: "主题", subscription: "订阅", followers: "粉丝", following: "关注", follow: "关注", play: "播放", pause: "暂停", queue: "播放队列", lyrics: "歌词", save: "保存", delete: "删除", close: "关闭", offline: "你已离线", logout: "退出登录", profile: "个人资料", settingsTitle: "设置", notificationTitle: "你的消息", noResults: "还没有回声", studio: "艺人工作室", support: "支持中心", admin: "管理控制台", public: "公开", private: "私密", album: "专辑", single: "单曲", verified: "认证艺人", createPlaylist: "创建播放列表", markAllRead: "全部标为已读", upgrade: "查看方案", currentPlan: "当前方案", register: "创建 Sonora 账户", artistRegister: "开启你的艺人旅程", shortcuts: "键盘快捷键" });

i18n.use(initReactI18next).init({ resources: { en: { translation: en }, es: { translation: es }, de: { translation: de }, fr: { translation: fr }, ru: { translation: ru }, "zh-CN": { translation: zh } }, lng: "en", fallbackLng: "en", interpolation: { escapeValue: false } });

export const locales: { value: Locale; label: string }[] = [
  { value: "en", label: "English" }, { value: "es", label: "Español" }, { value: "de", label: "Deutsch" },
  { value: "fr", label: "Français" }, { value: "ru", label: "Русский" }, { value: "zh-CN", label: "简体中文" },
];
export default i18n;
