import { Bell, Check, ChevronRight, CircleDollarSign, Download, Image, LockKeyhole, MonitorSmartphone, RotateCcw, SlidersHorizontal, Trash2, Users, X } from "lucide-react";
import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { useNavigate } from "react-router-dom";
import { locales } from "../../i18n";
import { RepositoryError, repository } from "../../repositories/localRepository";
import { canDownload, canEditAvatar, canUseRooms } from "../../domain/entitlements";
import { useDatabaseVersion, useSession } from "../../store/session";

export function SettingsPage() {
  const { t, i18n } = useTranslation(); const navigate = useNavigate(); const user = useSession()!; useDatabaseVersion(); const db = repository.database(); const [plansOpen, setPlansOpen] = useState(false); const [checkoutPlan, setCheckoutPlan] = useState<string | null>(null); const [message, setMessage] = useState(""); const [username, setUsername] = useState(user.username);
  useEffect(() => { document.documentElement.dataset.theme = user.theme; }, [user.theme]);
  const setLanguage = (locale: typeof user.locale) => { repository.updateSettings({ locale }); void i18n.changeLanguage(locale); };
  const purchase = () => { if (!checkoutPlan) return; try { repository.purchase(checkoutPlan); setCheckoutPlan(null); setPlansOpen(false); setMessage(t("checkoutComplete")); } catch (reason) { setMessage(reason instanceof RepositoryError ? reason.message : t("error")); } };
  const cycleAvatar = () => { const options = ["/media/avatars/user-basic.svg", "/media/avatars/user-silver.svg", "/media/avatars/user-gold.svg", "/media/avatars/user-artist-4.svg"]; const next = options[(Math.max(-1, options.indexOf(user.avatarUrl ?? "")) + 1) % options.length]; repository.updateAvatar(next); setMessage(t("avatarUpdated")); };
  return <div className="page settings-page"><header className="page-heading"><span className="eyebrow">{t("profile")}</span><h1>{t("settingsTitle")}</h1></header>
    {message && <div className="notice-line"><Check />{message}</div>}
    <section className="settings-section"><div className="settings-title"><SlidersHorizontal /><div><h2>{t("appearance")}</h2><p>{t("language")} · {t("theme")}</p></div></div><div className="settings-controls"><label>{t("language")}<select value={user.locale} onChange={(event) => setLanguage(event.target.value as typeof user.locale)}>{locales.map((locale) => <option value={locale.value} key={locale.value}>{locale.label}</option>)}</select></label><label>{t("theme")}<select value={user.theme} onChange={(event) => repository.updateSettings({ theme: event.target.value as typeof user.theme })}><option value="dark">{t("dark")}</option><option value="light">{t("light")}</option><option value="system">{t("system")}</option></select></label><label>{t("timezone")}<select value={user.timezone} onChange={(event) => repository.updateSettings({ timezone: event.target.value })}>{[user.timezone, "Asia/Tehran", "Europe/Berlin", "America/New_York", "Asia/Shanghai"].filter((value, index, list) => list.indexOf(value) === index).map((zone) => <option key={zone}>{zone}</option>)}</select></label></div></section>
    <section className="settings-section"><div className="settings-title"><Bell /><div><h2>{t("content")}</h2><p>{t("notificationMode")}</p></div></div><div className="settings-controls"><label className="switch-row"><span><strong>{t("explicitSetting")}</strong><small>{t("explicitMinor")}</small></span><input type="checkbox" checked={user.explicitContentEnabled} onChange={(event) => repository.updateSettings({ explicitContentEnabled: event.target.checked })} /></label><label>{t("notificationMode")}<select value={user.notificationPreference} onChange={(event) => repository.updateSettings({ notificationPreference: event.target.value as typeof user.notificationPreference })}><option value="all">{t("all")}</option><option value="important_only">{t("importantOnly")}</option><option value="max_five_daily">{t("maxFiveDaily")}</option><option value="muted">{t("muted")}</option></select></label></div></section>
    {user.kind === "consumer" && <><section className="subscription-card"><div className={`plan-orb ${user.subscription.tier}`}><CircleDollarSign /></div><div><span className="eyebrow">{t("currentPlan")}</span><h2>{t(user.subscription.tier)}</h2><p>{user.subscription.expiresAt ? new Intl.DateTimeFormat(user.locale, { dateStyle: "medium" }).format(new Date(user.subscription.expiresAt)) : t("basic")}</p></div><button className="button primary" onClick={() => setPlansOpen(true)}>{t("upgrade")}<ChevronRight /></button></section>
    <div className="entitlement-grid"><button className={canEditAvatar(user.subscription.tier) ? "enabled" : "disabled"} onClick={cycleAvatar} disabled={!canEditAvatar(user.subscription.tier)}><Image /><strong>{t("changeAvatar")}</strong><span>{t(canEditAvatar(user.subscription.tier) ? "available" : "profileImageGate")}</span></button><div className={canDownload(user.subscription.tier) ? "enabled" : "disabled"}><Download /><strong>{t("download")}</strong><span>{t(canDownload(user.subscription.tier) ? "available" : "basic")}</span></div><div className={canUseRooms(user.subscription.tier) ? "enabled" : "disabled"}><Users /><strong>{t("groupListening")}</strong><span>{t("roomsGate")}</span></div></div></>}
    <section className="settings-section danger-zone"><div className="settings-title"><MonitorSmartphone /><div><h2>{t("account")}</h2><p>{user.email}</p></div></div><div className="settings-controls">{user.kind === "consumer" && <label>{t("username")}<div className="inline-control"><input value={username} onChange={(event) => setUsername(event.target.value)} /><button className="button ghost" onClick={() => { try { repository.updateUsername(username); setMessage(t("done")); } catch (reason) { setMessage(reason instanceof RepositoryError ? reason.message : t("error")); } }}>{t("updateUsername")}</button></div><small>{t("usernameHelp")}</small></label>}<div className="danger-actions"><button className="button ghost" onClick={() => { if (confirm(t("resetDemoHelp"))) { repository.reset(); navigate("/login"); } }}><RotateCcw />{t("resetDemo")}</button><button className="button danger" onClick={() => { if (confirm(t("deleteWarning"))) { repository.deleteAccount(); navigate("/login"); } }}><Trash2 />{t("deleteAccount")}</button></div></div></section>
    {plansOpen && <div className="modal-backdrop"><div className="modal plan-modal"><div className="modal-head"><div><span className="eyebrow">{t("demoSimulation")}</span><h2>{t("upgrade")}</h2></div><button className="icon-button" onClick={() => setPlansOpen(false)}><X /></button></div><div className="plan-grid">{db.plans.filter((plan) => plan.isAvailable).map((plan) => <button className={`plan-choice ${plan.tier} ${checkoutPlan === plan.id ? "selected" : ""}`} key={plan.id} onClick={() => setCheckoutPlan(plan.id)}><span>{t(plan.tier)} · {plan.durationMonths} {t("monthShort")}</span><strong>{Math.round(plan.finalPriceRial / 10).toLocaleString(user.locale)} {t("toman")}</strong><small>{plan.discountPercent ? `${plan.discountPercent}% ${t("discount")}` : t("perMonth")}</small>{checkoutPlan === plan.id && <Check />}</button>)}</div>{message && <p className="form-error">{message}</p>}<div className="checkout-note"><LockKeyhole /><span>{t("demoSimulation")}</span></div><button className="button primary wide" onClick={purchase} disabled={!checkoutPlan}>{t("confirm")}</button></div></div>}
  </div>;
}
