# Generated by Codex on 2026-06-22

import apps.accounts.models
import django.contrib.auth.validators
from django.db import migrations, models


def blank_usernames_to_null(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(username="").update(username=None)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_email_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                error_messages={"unique": "A user with that username already exists."},
                max_length=150,
                null=True,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
            ),
        ),
        migrations.RunPython(blank_usernames_to_null, migrations.RunPython.noop),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
    ]
